var express = require("express");
var bodyparser = require("body-parser");
var cors = require("cors");
var app = express();
app.use(bodyparser.json());
app.use(bodyparser.urlencoded({extended:false}));
app.use(cors());
var login = require("./login/login");
app.use("/login",login);
var about = require("./about/about");
app.use("/about",about);
var home = require("./home/home");
app.use("/home",home);
var contact = require("./contact/contact");
app.use("/contact",contact);
var logout = require("./logout/logout");
app.use("/logout",logout);
app.listen(8080);
console.log("Server Listening the port no.8080");